baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pbdoom.imustafin.tatar" # the base hostname & protocol for your site, e.g. http://example.com

langs:
  - en
  - ru
  - tt

plugins:
  - jemoji
  - jekyll-postcss
  - jekyll-node-module
  - jekyll-seo-tag

title: PBDoom
tagline: Doom for PocketBook eInk devices
author:
  name: Ilgiz Mustafin
  url: https://imustafin.tatar
lang: en
webmaster_verifications:
  yandex: 27b0933fb2cb476e

postcss:
  cache: false

excerpt_separator: '<!-- excerpt -->'

prose_class: 'prose lg:prose-lg prose-slate prose-code:before:hidden prose-code:after:hidden'
prose_class_unsized: 'prose prose-slate prose-code:before:hidden prose-code:after:hidden'
link_class: 'text-[#111827] underline'

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: ru
    values:
      lang: ru
  - scope:
      path: tt
    values:
      lang: tt
  - scope:
      path: ru
      type: posts
    values:
      lang: ru
