source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-postcss', '~> 0.5.0'
  gem 'jekyll-node-module', '~> 0.1.1'
  gem 'jemoji', '~> 0.13.0'
  gem 'jekyll-seo-tag', '~> 2.8'
end

gem 'rake', '~> 13.0', '>= 13.0.6'
