name: Update to gh-pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Keep only pages dir
        run: |
          mv pages /tmp/pages
          rm -rf *
          mv /tmp/pages/* .

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Refresh releases
        run: |
          bundle exec rake releases

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
